
use perrera;

SHOW TRIGGERS;

/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UN NUEVO ROL*/
DELIMITER $$
CREATE TRIGGER add_id_rol
BEFORE INSERT ON roles
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM roles);
END$$
DELIMITER ;

/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UN NUEVO ANIMAL*/
DELIMITER $$
CREATE TRIGGER add_id_animal
BEFORE INSERT ON animales
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM animales);
END$$
DELIMITER ;


/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UN NUEVO VOLUNTARIO*/
DELIMITER $$
CREATE TRIGGER add_id_voluntario
BEFORE INSERT ON voluntarios
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM voluntarios);
END$$
DELIMITER ;


/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UN NUEVO Empleado*/
DELIMITER $$
CREATE TRIGGER add_id_empleados
BEFORE INSERT ON empleados
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM empleados);
END$$
DELIMITER ;



/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UNA NUEVA TAREA*/
DELIMITER $$
CREATE TRIGGER add_id_tareas
BEFORE INSERT ON tareas
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM tareas);
END$$
DELIMITER ;



/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UN NUEVO VETERINARIO*/
DELIMITER $$
CREATE TRIGGER add_id_veterinarios
BEFORE INSERT ON veterinarios
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM veterinarios);
END$$
DELIMITER ;



/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UNA NUEVA ESPECIE*/
DELIMITER $$
CREATE TRIGGER add_id_especies
BEFORE INSERT ON especies
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM especies);
END$$
DELIMITER ;



/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UNA NUEVA ESPECIE*/
DELIMITER $$
CREATE TRIGGER add_id_categorias_existencia
BEFORE INSERT ON categorias_existencia
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM categorias_existencia);
END$$
DELIMITER ;



/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UNA NUEVA ESPECIE*/
DELIMITER $$
CREATE TRIGGER add_id_existencias
BEFORE INSERT ON existencias
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM existencias);
END$$
DELIMITER ;




/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UN NUEVO ADOPTANTE*/
DELIMITER $$
CREATE TRIGGER add_id_adoptante
BEFORE INSERT ON adoptante
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM adoptante);
END$$
DELIMITER ;



/*TRIGGER QUE SALTA ANTES DE LA INSERCIÓN DE UNA NUEVA JAULA*/
DELIMITER $$
CREATE TRIGGER add_id_jaulas
BEFORE INSERT ON jaulas
FOR EACH ROW
BEGIN
	SET NEW.id = (SELECT IFNULL(MAX(id) + 1, 1) FROM jaulas);
END$$
DELIMITER ;