-- MySQL Script generated by MySQL Workbench
-- Sun Apr 23 19:31:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema perrera
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `perrera` ;

-- -----------------------------------------------------
-- Schema perrera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `perrera` DEFAULT CHARACTER SET utf8 ;
USE `perrera` ;

-- -----------------------------------------------------
-- Table `perrera`.`adoptante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`adoptante` ;

CREATE TABLE IF NOT EXISTS `perrera`.`adoptante` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `apellidos` VARCHAR(120) NOT NULL DEFAULT 'No especificado',
  `fecha_nacimiento` DATE NOT NULL DEFAULT NOW(),
  `NIF` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `correo` VARCHAR(150) NOT NULL DEFAULT 'No especificado',
  `telf` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `direccion` VARCHAR(255) NOT NULL DEFAULT 'No especificado',
  `preferencia_adopcion` TINYINT NOT NULL DEFAULT 0,
  `animales_id` INT NOT NULL,
  `estado_solicitud` TINYINT NOT NULL DEFAULT 1,
  `fecha_solicitud` TIMESTAMP NOT NULL DEFAULT NOW(),
  `tiempo_espera` INT NOT NULL DEFAULT 0,
  `estado_adopcion` TINYINT NULL,
  `fecha_adopcion` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `animales_id`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC),
  INDEX `fk_adoptante_animales1_idx` (`animales_id` ASC),
  CONSTRAINT `fk_adoptante_animales1`
    FOREIGN KEY (`animales_id`)
    REFERENCES `perrera`.`animales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`animales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`animales` ;

CREATE TABLE IF NOT EXISTS `perrera`.`animales` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT '-',
  `especies_id` INT NOT NULL,
  `raza` VARCHAR(30) NOT NULL DEFAULT 'No especificada',
  `genero` CHAR(1) NOT NULL DEFAULT 'M',
  `tamanio` VARCHAR(20) NOT NULL DEFAULT '-',
  `peso` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `colores` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `personalidad` VARCHAR(45) NOT NULL DEFAULT '-',
  `fech_nac` DATE NOT NULL DEFAULT '1800-01-01',
  `estado_adopcion` VARCHAR(50) NOT NULL DEFAULT 'Disponible',
  `estado_salud` VARCHAR(50) NOT NULL DEFAULT 'Bien',
  `necesidades_especiales` CHAR(2) NOT NULL DEFAULT 'NO',
  `otras_observaciones` VARCHAR(255) NOT NULL DEFAULT '-',
  `jaulas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `especies_id`, `jaulas_id`),
  INDEX `fk_animales_jaulas1_idx` (`jaulas_id` ASC),
  INDEX `fk_animales_especies1_idx` (`especies_id` ASC),
  CONSTRAINT `fk_animales_jaulas1`
    FOREIGN KEY (`jaulas_id`)
    REFERENCES `perrera`.`jaulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animales_especies1`
    FOREIGN KEY (`especies_id`)
    REFERENCES `perrera`.`especies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`animales_has_veterinarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`animales_has_veterinarios` ;

CREATE TABLE IF NOT EXISTS `perrera`.`animales_has_veterinarios` (
  `animales_id` INT NOT NULL,
  `veterinarios_id` INT NOT NULL,
  `motivo` VARCHAR(150) NOT NULL DEFAULT 'No especificado',
  `fecha_atencion` TIMESTAMP NOT NULL DEFAULT NOW(),
  `diagnostico` VARCHAR(200) NOT NULL DEFAULT 'No especificado',
  `procedimientos` VARCHAR(200) NOT NULL DEFAULT 'No especificado',
  `medicamentos` VARCHAR(200) NOT NULL DEFAULT 'No especificado',
  `comentarios` VARCHAR(255) NULL,
  `coste` DECIMAL(7,2) NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`animales_id`, `veterinarios_id`),
  INDEX `fk_animales_has_veterinarios_veterinarios1_idx` (`veterinarios_id` ASC),
  INDEX `fk_animales_has_veterinarios_animales1_idx` (`animales_id` ASC),
  CONSTRAINT `fk_animales_has_veterinarios_animales1`
    FOREIGN KEY (`animales_id`)
    REFERENCES `perrera`.`animales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animales_has_veterinarios_veterinarios1`
    FOREIGN KEY (`veterinarios_id`)
    REFERENCES `perrera`.`veterinarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`categorias_existencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`categorias_existencia` ;

CREATE TABLE IF NOT EXISTS `perrera`.`categorias_existencia` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT '-',
  `descripcion` VARCHAR(100) NOT NULL DEFAULT '-',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`duenios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`duenios` ;

CREATE TABLE IF NOT EXISTS `perrera`.`duenios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `apellidos` VARCHAR(120) NOT NULL DEFAULT 'No especificado',
  `fecha_nacimiento` DATE NOT NULL DEFAULT NOW(),
  `NIF` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `correo` VARCHAR(150) NOT NULL DEFAULT 'No especificado',
  `telf` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `direccion` VARCHAR(255) NOT NULL DEFAULT 'No especificado',
  `animales_id` INT NOT NULL,
  `permiso_visita` TINYINT NOT NULL DEFAULT 1,
  `fecha_ultima_visita` TIMESTAMP NOT NULL DEFAULT NOW(),
  `observaciones` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `animales_id`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC),
  INDEX `fk_Dueños_animales1_idx` (`animales_id` ASC),
  CONSTRAINT `fk_Dueños_animales1`
    FOREIGN KEY (`animales_id`)
    REFERENCES `perrera`.`animales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`empleados` ;

CREATE TABLE IF NOT EXISTS `perrera`.`empleados` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `apellidos` VARCHAR(120) NOT NULL DEFAULT 'No especificado',
  `NIF` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `correo` VARCHAR(150) NOT NULL DEFAULT 'No especificado',
  `passwd` VARCHAR(255) NOT NULL DEFAULT 'No especificado',
  `salt` VARCHAR(40) NOT NULL DEFAULT 'No especificado',
  `telf` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_id`),
  INDEX `fk_empleados_roles1_idx` (`roles_id` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  CONSTRAINT `fk_empleados_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `perrera`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`encargados_animales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`encargados_animales` ;

CREATE TABLE IF NOT EXISTS `perrera`.`encargados_animales` (
  `animales_id` INT NOT NULL,
  `empleados_id` INT NOT NULL,
  `fecha_asignacion` TIMESTAMP NOT NULL DEFAULT NOW(),
  `fecha_desasignacion` TIMESTAMP NULL,
  PRIMARY KEY (`animales_id`, `empleados_id`),
  INDEX `fk_encargados_animales_empleados1_idx` (`empleados_id` ASC),
  CONSTRAINT `fk_encargados_animales_animales1`
    FOREIGN KEY (`animales_id`)
    REFERENCES `perrera`.`animales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encargados_animales_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `perrera`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`especies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`especies` ;

CREATE TABLE IF NOT EXISTS `perrera`.`especies` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'No especificado',
  `descripcion` VARCHAR(100) NOT NULL DEFAULT '-',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idespecies_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`existencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`existencias` ;

CREATE TABLE IF NOT EXISTS `perrera`.`existencias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `descripcion` VARCHAR(100) NULL,
  `cantidad` INT NOT NULL DEFAULT 0,
  `precio_unidad` DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  `categorias_existencia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categorias_existencia_id`),
  INDEX `fk_existencias_categorias_existencia1_idx` (`categorias_existencia_id` ASC),
  CONSTRAINT `fk_existencias_categorias_existencia1`
    FOREIGN KEY (`categorias_existencia_id`)
    REFERENCES `perrera`.`categorias_existencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`factura_existencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`factura_existencia` ;

CREATE TABLE IF NOT EXISTS `perrera`.`factura_existencia` (
  `existencias_id` INT NOT NULL,
  `proveedores_id` INT NOT NULL,
  `num_factura` INT NULL,
  `fecha_adquisicion` TIMESTAMP NOT NULL DEFAULT NOW(),
  `factura_pdf` LONGBLOB NULL,
  PRIMARY KEY (`existencias_id`, `proveedores_id`),
  INDEX `fk_existencias_has_proveedores_proveedores1_idx` (`proveedores_id` ASC),
  INDEX `fk_existencias_has_proveedores_existencias1_idx` (`existencias_id` ASC),
  CONSTRAINT `fk_existencias_has_proveedores_existencias1`
    FOREIGN KEY (`existencias_id`)
    REFERENCES `perrera`.`existencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_existencias_has_proveedores_proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `perrera`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`imagenes_animales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`imagenes_animales` ;

CREATE TABLE IF NOT EXISTS `perrera`.`imagenes_animales` (
  `id` INT NOT NULL,
  `id_animal` INT NOT NULL,
  `img` LONGBLOB NULL,
  PRIMARY KEY (`id`, `id_animal`),
  INDEX `fk_imagenes_animales_animales_idx` (`id_animal` ASC),
  CONSTRAINT `fk_imagenes_animales_animales`
    FOREIGN KEY (`id_animal`)
    REFERENCES `perrera`.`animales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`jaulas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`jaulas` ;

CREATE TABLE IF NOT EXISTS `perrera`.`jaulas` (
  `id` INT NOT NULL,
  `ubicacion` VARCHAR(100) NOT NULL DEFAULT 'A-00',
  `tamanio` INT NOT NULL DEFAULT 0,
  `ocupada` TINYINT NOT NULL DEFAULT 0,
  `estado_comida` TINYINT NOT NULL DEFAULT 0,
  `estado_limpieza` TINYINT NOT NULL DEFAULT 0,
  `otros_comentarios` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `perrera`.`proveedores` (
  `id` INT NOT NULL,
  `CIF` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `direccion` VARCHAR(255) NOT NULL DEFAULT 'No especificado',
  `correo` VARCHAR(150) NOT NULL DEFAULT 'No especificado',
  `telf` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `estado_proveedor` TINYINT NOT NULL DEFAULT 1,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `CIF_UNIQUE` (`CIF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`roles` ;

CREATE TABLE IF NOT EXISTS `perrera`.`roles` (
  `id` INT NOT NULL,
  `rol` VARCHAR(45) NOT NULL DEFAULT 'admin',
  `descripcion` VARCHAR(150) NOT NULL DEFAULT '-',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`tareas` ;

CREATE TABLE IF NOT EXISTS `perrera`.`tareas` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `descripcion` VARCHAR(100) NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT NOW(),
  `fecha_finalizacion` TIMESTAMP NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`tareas_asignadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`tareas_asignadas` ;

CREATE TABLE IF NOT EXISTS `perrera`.`tareas_asignadas` (
  `id` INT NOT NULL,
  `tareas_id` INT NOT NULL,
  `empleados_id` INT NULL,
  `voluntarios_id` INT NULL,
  `jaulas_id` INT NULL,
  `estado_asignacion` TINYINT NOT NULL DEFAULT 0,
  `fecha_asignacion` TIMESTAMP NULL,
  `fecha_finalizacion` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `tareas_id`, `empleados_id`, `voluntarios_id`, `jaulas_id`),
  INDEX `fk_tareas_asignadas_voluntarios1_idx` (`voluntarios_id` ASC),
  INDEX `fk_tareas_asignadas_empleados1_idx` (`empleados_id` ASC),
  INDEX `fk_tareas_asignadas_jaulas1_idx` (`jaulas_id` ASC),
  INDEX `fk_tareas_asignadas_tareas1_idx` (`tareas_id` ASC),
  CONSTRAINT `fk_tareas_asignadas_voluntarios1`
    FOREIGN KEY (`voluntarios_id`)
    REFERENCES `perrera`.`voluntarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_asignadas_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `perrera`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_asignadas_jaulas1`
    FOREIGN KEY (`jaulas_id`)
    REFERENCES `perrera`.`jaulas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_asignadas_tareas1`
    FOREIGN KEY (`tareas_id`)
    REFERENCES `perrera`.`tareas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`veterinarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`veterinarios` ;

CREATE TABLE IF NOT EXISTS `perrera`.`veterinarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `apellidos` VARCHAR(120) NOT NULL DEFAULT 'No especificado',
  `correo` VARCHAR(150) NOT NULL DEFAULT 'No especificado',
  `telf` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `horarios` VARCHAR(45) NULL,
  `otra_informacion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `perrera`.`voluntarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perrera`.`voluntarios` ;

CREATE TABLE IF NOT EXISTS `perrera`.`voluntarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL DEFAULT 'No especificado',
  `apellidos` VARCHAR(120) NOT NULL DEFAULT 'No especificado',
  `fech_nac` DATE NOT NULL DEFAULT NOW(),
  `NIF` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `correo` VARCHAR(150) NOT NULL DEFAULT 'No especificado',
  `telf` VARCHAR(15) NOT NULL DEFAULT 'No especificado',
  `experiencia_previa` TINYINT NOT NULL DEFAULT 1,
  `disponibilidad` TINYINT NOT NULL DEFAULT 1,
  `informacion_relevante` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
