-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 10:54:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tienda_animales
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tienda_animales` ;

-- -----------------------------------------------------
-- Schema tienda_animales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_animales` DEFAULT CHARACTER SET utf8 ;
USE `tienda_animales` ;

-- -----------------------------------------------------
-- Table `tienda_animales`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Roles` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_animales`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `telefono` VARCHAR(11) NULL,
  `correo` VARCHAR(100) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(4000) NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  INDEX `fk_Usuarios_Roles1_idx` (`id_rol` ASC),
  CONSTRAINT `fk_Usuarios_Roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `tienda_animales`.`Roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_animales`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_animales`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Productos` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `Categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_Productos_Categoria1_idx` (`Categoria_id_categoria` ASC),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_producto` ASC),
  CONSTRAINT `fk_Productos_Categoria1`
    FOREIGN KEY (`Categoria_id_categoria`)
    REFERENCES `tienda_animales`.`Categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_animales`.`Proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Proveedores` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `id_proveedor_UNIQUE` (`id_proveedor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_animales`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `precio_final` DECIMAL NOT NULL,
  `Usuarios_id_usuario1` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_Pedidos_Usuarios1_idx` (`Usuarios_id_usuario1` ASC),
  UNIQUE INDEX `id_pedido_UNIQUE` (`id_pedido` ASC),
  CONSTRAINT `fk_Pedidos_Usuarios1`
    FOREIGN KEY (`Usuarios_id_usuario1`)
    REFERENCES `tienda_animales`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_animales`.`Detalles_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Detalles_pedido` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Detalles_pedido` (
  `id_detallesPed` INT NOT NULL AUTO_INCREMENT,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Pedidos_id_pedido` INT NOT NULL,
  `Productos_id_producto` INT NOT NULL,
  PRIMARY KEY (`id_detallesPed`, `Pedidos_id_pedido`, `Productos_id_producto`),
  INDEX `fk_Detalles_pedido_Pedidos1_idx` (`Pedidos_id_pedido` ASC),
  INDEX `fk_Detalles_pedido_Productos1_idx` (`Productos_id_producto` ASC),
  UNIQUE INDEX `id_detallesPed_UNIQUE` (`id_detallesPed` ASC),
  CONSTRAINT `fk_Detalles_pedido_Pedidos1`
    FOREIGN KEY (`Pedidos_id_pedido`)
    REFERENCES `tienda_animales`.`Pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalles_pedido_Productos1`
    FOREIGN KEY (`Productos_id_producto`)
    REFERENCES `tienda_animales`.`Productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_animales`.`Detalles_proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tienda_animales`.`Detalles_proveedores` ;

CREATE TABLE IF NOT EXISTS `tienda_animales`.`Detalles_proveedores` (
  `Proveedores_id_proveedor` INT NOT NULL,
  `Productos_id_producto` INT NOT NULL,
  PRIMARY KEY (`Proveedores_id_proveedor`, `Productos_id_producto`),
  INDEX `fk_Proveedores_has_Productos_Productos1_idx` (`Productos_id_producto` ASC),
  INDEX `fk_Proveedores_has_Productos_Proveedores1_idx` (`Proveedores_id_proveedor` ASC),
  CONSTRAINT `fk_Proveedores_has_Productos_Proveedores1`
    FOREIGN KEY (`Proveedores_id_proveedor`)
    REFERENCES `tienda_animales`.`Proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedores_has_Productos_Productos1`
    FOREIGN KEY (`Productos_id_producto`)
    REFERENCES `tienda_animales`.`Productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
